### ISSUE TITLE
Impact Databank Reports link in SND article footer box

### ISSUE THREAD

**Issue by JoeMeyerson** [mshanken/Shanken-News-Daily#20]
Steve, please update the footer box in SND articles by incrementing each year: 

change 

> "2017 data and 2018 projections"

to 

> "2018 data and 2019 projections"

and change 

> "order your 2018 impact databank reports"

to 

> "order your 2019 impact databank reports"

Also, please change the target URL from 

`http://www.shankennewsdaily.com/index.php/impact-databank-report/`

to

`https://winespectator.wufoo.com/forms/q1tp0ys41mdhey0/`

Please see the attached screenshot for reference:

![SND-box](https://user-images.githubusercontent.com/1508820/61328824-e1431800-a7e9-11e9-80c0-d60afee701fb.png)

**Comment by szhukov86** [comment]
This went live! @swcannizzaro @JoeMeyerson
